/*
Author:     Jason Smith
Project:    Inventory Management
Date:       8-17-17
WGU Class:  C482
 */
package Views;

import classes.files.Main;
import classes.files.Parts;
import java.net.URL;
import java.util.ResourceBundle;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;
import javafx.scene.control.Label;
import javafx.scene.control.RadioButton;
import javafx.scene.control.TextField;
import javafx.scene.control.ToggleGroup;
import javafx.stage.Stage;

/**
 * FXML Controller class
 *
 * @author Jason Smith
 */
public class AddPartController implements Initializable {

    private Main main; //REFERENCE TO MAIN
    private Stage addPartStage;

    private Parts partObject;
    private int ID;
    private String dialogMessage;

    @FXML
    private TextField partNameField, inventoryField, priceField, partSourceField, minInventoryField, maxInventoryField;

    @FXML
    private Button saveBtn, cancelBtn;

    @FXML
    private Label partSourceLabel;

    @FXML
    private RadioButton inHouseField, outSourcedField;

    @FXML
    private ToggleGroup partSourceBtnGroup;

    boolean inHouse;

    public void setStage(Stage stage) {
        this.addPartStage = stage;
    }

    @FXML
    private void inHouseClicked() {
        partSourceLabel.setText("Machine ID");

    }

    @FXML
    private void outSourcedClicked() {
        partSourceLabel.setText("Company Name");

    }

    /**
     * Initializes the controller class.
     *
     * @param url
     * @param rb
     */
    @Override
    public void initialize(URL url, ResourceBundle rb) {
        // TODO
    }

    @FXML
    private void saveBtn(ActionEvent event) {
        try {
            inHouse = inHouseField.isSelected();
            ID = main.getAutogeneratedID();
            ID += 1;
            main.setAutogeneratedID(ID);
            partObject = new Parts();
            partObject.setName(partNameField.getText());
            partObject.setInventoryCount(Integer.parseInt(inventoryField.getText()));
            partObject.setPrice(Double.parseDouble(priceField.getText()));
            partObject.setMaxInventory(Integer.parseInt(maxInventoryField.getText()));
            partObject.setMinInventory(Integer.parseInt(minInventoryField.getText()));
            partObject.setPartSource(partSourceField.getText());
            partObject.setIsInHouse(inHouse);

            partObject.setID(ID);
            //TEST INVENTORY VALIDATION

            if (partObject.testValidInventoryNumbers()) {//IF TEST IS GOOD ADD THE OBJECT TO LIST IN MAIN
                main.getPartData().add(partObject);
            } else {
                dialogMessage = partObject.getMessage();
                main.showWarning(dialogMessage);
            }
            //CLEAR ALL THE FIELDS
            partNameField.clear();
            inventoryField.clear();
            priceField.clear();
            partSourceField.clear();
            minInventoryField.clear();
            maxInventoryField.clear();
        } catch (NumberFormatException error) {
            dialogMessage = ("\n"
                    + "The data you have entered is\n"
                    + "incorrect or is missing.\n"
                    + "Please fix the information");
            main.showWarning(dialogMessage);
        }

    }

    @FXML
    private void cancelBtn() {
        dialogMessage = "\n"
                + "Are you sure you want"
                + "\n"
                + "to cancel adding this part?"
                + "\n";
        main.showDeleteWarning(dialogMessage);
        if (main.getYesOrNo()) {
            addPartStage.close();
        }
    }

    public void setMain(Main main) {
        this.main = main;
    }

}
